### ISSUE TITLE
[1장] 타입스크립트 알아보기

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#1]
퀴즈 예시

```
Q. 퀴즈

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by hyoribogo** [comment]
Q. 퀴즈 예시
- 1 + 1 = ?

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
창문
</div>
</details>

**Comment by JIY00N2** [comment]
Q. 퀴즈 

`string` 또는 `number` 타입인 값을 항상 `number`로 정제하는 경우

다음은 타입 체커는 통과하지만 잘못된 방법 입니다.
올바르게 수정해주세요 !
```ts
function asNumber(val: number | string): number {
  return val as number;
}
```
형식
```ts
function asNumber() {
  return
}
```

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
<img width="321" alt="image" src="https://github.com/prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study/assets/109654823/f9082631-8650-44ac-a669-42ee215908be">
</div>
</details>

**Comment by dlwl98** [comment]
Q. 퀴즈

**다음 타입스크립트 코드에서 에러가 나는 부분을 찾고, 어떻게 해결할 수 있는지 서술하시오**

```ts
interface Vector {
  x: number;
  y: number;
  z: number;
}

const vector: Vector = { x: 1, y: 2, z: 3 };
for (const axis in vector) {
  console.log(vector[axis]);
}
```

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
<span>에러가 나는 부분: </span>
<code>vector[axis]</code>
<br/>
<br/>
<span>해결 방법 1: <code>타입 단언</code></span>
<pre>
<code>
/** vector[axis as keyof typeof vector] */
vector[axis as keyof Vector]
</code>
</pre>
</div>
<span>해결 방법 2: <code>타입 선언</code></span>
<pre>
<code>
let axis: keyof Vector
for (axis in vector) {
  console.log(vector[key])
}
</code>
</pre>
</div>
<span>해결 방법 3: <code>인덱스 시그니처</code></span>
<br/>
<pre>
<code>
type Vector = {
  [key: string]: number;
  x: number;
  y: number;
  z: number;
}
</code>
</pre>
</div>
</details>

**Comment by oaoong** [comment]
Q. 퀴즈
아래 코드에 대해 1. 런타임에서의 출력 결과와 2. 타입 시스템에서 에러를 표시하는 부분과 그 이유를 서술하시오.
```typescript
class Person {
  name: string
  age: number
  constructor(name: string, age: number) {
    this.name = name
    this.age = age
  }
}

function getName(user: Person) {
    console.log(user.name)
}

const john = new Person('John Doe', 30)
const jane = {
  name: 'Jane Doe',
  age: 25,
}

getName(john)
getName(jane)
```

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
1. <br/>
John Doe <br/>
Jane Doe
<br/>
<br/>
2. <br/>
에러가 발생하지 않는다. <br/>
타입스크립트는 구조적 타이핑을 통해 에러를 감지하기 때문에, 클래스명으로서 타입으로도 사용 가능한 Person 타입과 jane에서 할당값을 통해 추론한 인스턴스의 내용이 일치하므로 getName()의 인자로 전달함에 있어서 문제가 없다.
</div>
</details>

**Comment by Jeong-Taeho** [comment]
Q. 런타임에는 타입 체크가 불가능하지만 런타임 때 타입 정보를 유지할 수 있도록 하는 방법 중 틀린 것을 모두 골라주세요.

1. 런타임에 접근 가능한 타입 정보를 암시적으로 저장하는 태그기법
2. 속성이 존재하는지 체크
3. class로 만들기
4. 타입을 오버로딩 하기

<details>
<summary>퀴즈 정답</summary>
  
1. 런타임에 접근 가능한 타입 정보를 `명시적`으로 저장하는 태그기법인 `tagged union` 이 있습니다.
2. 속성이 존재하는지 체크 
3. 타입과 값을 둘 다 사용하기위해 타입을 클래스로 만들기

</details>

Q. 번역과 컴파일이 합쳐져 나온 신조어로 소스코드를 동일한 동작을 하는 다른 형태의 소스코드 (다른 버전, 다른 언어)로 변환하는 행위를 뜻하는 이 단어는 무엇일까요?

<details>
<summary>퀴즈 정답</summary>
  
트랜스파일(transpile)
</details>

**Comment by khakhiD** [comment]
[실제 프론트엔드 면접 질문]
**Q. 타입스크립트에서 type이나 interface들을 사용하게 되면 코드가 많아지게 됩니다. 이에 대한 성능 처리를 어떻게 하시나요?**


<details>
<summary>퀴즈 정답</summary>
<div markdown="1">
<hr>

면접관 의도가 무엇인지 확신할 수 없으나, `면접자가 타입스크립트 동작 과정을 알고 있는지 테스트 해보려는 질문인 것 같다`고 합니다. (by 김의중 우아한형제들 개발자님) <strong>타입스크립트는 JS 런타임에 영향을 주지 않는다</strong>는 1장 내용을 생각하시면 될 것 같습니다.


- 타입이 제거(erased types)된 자바스크립트 파일로 변환이 되기 때문에 성능에 영향을 미치지 않는다.
- 런타임 오버헤드가 없고 빌드타임 오버헤드가 있다는 문제점 지적하기
- 하지만 TS의 버전이 올라갈 수록 빌드타임 오버헤드가 거의 무시할 수준으로 떨어지고 있다.
- ES 버전 호환에 따른 성능 오버헤드에 대한 이야기로 넘어가기


정도가 좋은 답변이 될 수 있을 것 같습니다.

<hr />

</div>
</details>
