### ISSUE TITLE
[8장][지윤] 타입스크립트로 마이그레이션하기

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#100]
### 퀴즈
O,X 퀴즈 입니다!
1. 마이그레이션의 첫 단계는 외부 API 호출과 서드파티 모듈에 대한 @types를 추가하는 것이다.
2. 이상한 설계를 발견하면, 바로 리팩토링 한다.
3. 마이그레이션 중간 단계에서 타입 정보를 유지하기 위해 타입스크립트에서도 JSDoc 주석을 필요시에 활용할 수 있다.
4. 타입스크립트에서 use strict 모드를 사용해도 된다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. O
2. X
3. O
4. X

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- O
- X
- X
- X
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
o x x x
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. O
2. X
3. X 헐랭
4. X

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. O
2. X
3. X
4. X

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. O
2. X
3. X
4. X (사용할 필요 없음)

</div>
</details>
