### ISSUE TITLE
[2장][이진욱]: 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by dlwl98** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#15]
### 퀴즈

퀴즈는 없습니다.
대신 2장의 진욱.md 아이템8 부분의 다형성 this 파트를 꼭 읽어보세요

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
읽으셨나요
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
읽었습니다.
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">    
읽었습니다
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

굿

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
내공냠냠
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
읽었슴다
</div>
</details>
