### ISSUE TITLE
[2장][이지윤]: 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#16]
### 퀴즈

퀴즈
```ts

interface Person {
  name: string;
}
interface Lifespan {
  birth: Date;
  death?: Date;
}
type K = keyof (Person | Lifespan); // 답을 맞춰주세요
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
Type is never<br>
유니온이여도 공통된 속성이 있으면 통과되지만, 없으면 정해질 수 없어서 never
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>답안</summary>
<div markdown="1">
never
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

never

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
// never 타입
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
never
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
never
</div>
</details>
