### ISSUE TITLE
[2장][정태호]: 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#19]
### 퀴즈
1. 아래 코드에서는 주석과 같은 오류가 발생합니다. 오류가 발생하는 이유와 오류가 사라질 수 있는 두 가지 방법을 작성해주세요!

```ts
interface Options {
  title: string;
  darkMode?: boolean;
}
const o: Options = {darkmode: true, title: "Ski Free"}  // Error
// 개체 리터럴은 알려진 속성만 지정할 수 있지만 'Options' 형식에 'darkmode'이(가) 없습니다.
```
### 답

<details>
<summary>정답</summary>
<div markdown="1">

- 객체리터럴에서는 잉여 속성 체크가 수행되기 때문에 올바른 속성명이 작성되지 않아 오류가 발생한다.

1. 임시변수 사용
```ts    
const intermediate = {darkmode: true, title: "Ski Free"};
const o: Options = intermediate;
```

2. 단언문 사용 및 오타 수정
```ts
const o = {darkmode: true, title: 'Ski Free'} as OPtions;
```
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>답안</summary>
<div markdown="1">
1. darkMode를 darkmode로 바꾼다.(오타수정)
2. 임시변수를 사용한다.
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">    
변수를 미리 할당해서 사용한다.

const temp =  {darkmode: true, title: "Ski Free"} ;
const o: Options = temp;

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

### 오류가 발생하는 이유
darkmode에서 'm'을 대문자로 써야하는데 오타를 냄. 공통 속성 체크에서 out

### 오류가 사라질 수 있는 두 가지 방법
1. 오타를 올바르게 바꿔요.
2. 인덱스 시그니처를 지정해요. `[other: string]: unknown`

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
잉여 속성 체크를 통과하지 못함.
1. darkmode 오타를 darkMode로 바로잡는다.
2. 임시 변수에 할당 후 재할당한다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">


**발생 이유**: 객체 리터럴을 사용하면 잉여 속성 체크가 일어나 알 수없는 속성을 허용하지 않기 때문에.


**수정**:
1) `darkmode` 오타를 `darkMode`로 수정한다.

2) 변수 `o`에 임시 객체 변수를 사용하여 할당한다.

</div>
</details>
