### ISSUE TITLE
[2장][신동호]: 타입스크립트의 타입 시스템 

### ISSUE THREAD

**Issue by khakhiD** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#22]
### 퀴즈

다음 코드에서 타입 체크 에러가 발생하는 부분이 있는지 확인해주세요.
```ts
const a = "hello";
const b = new String("hi");

function capFirstChar (input: String) {
  return input.charAt(0).toUpperCase() + input.slice(1);
}

capFirstChar(a);
capFirstChar(b);
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
타입 체크 에러 없음!

- String 객체 타입에는 string 타입이 할당될 수 없으나, string 타입에는 String 객체가 할당될 수 있다.
- 객체 래퍼 타입 사용을 피하세요!
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
에러 없음... string은 String에 할당 가능 반대는 불가
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
`에러 없음` string 타입에는 String 타입이 할당될 수 있기 때문
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>답안</summary>
<div markdown="1">
에러 없다.
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
return input.charAt(0).toUpperCase() + input.slice(1);
```

여기서 더하는 과정에서 에러가 나지 않을까요?

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
string 원시 타입은 String 래퍼 타입에 할당 가능이라 에러 없음
</div>
</details>
