### ISSUE TITLE
[2장][정재희]: 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#23]
### 퀴즈

다음 코드에서 (1), (2), (3), (4)의 타입 체크 결과를 예측해보세요.
```typescript
type User = {
  id: number;
  name: string;
};

type PartialUser = {
  id?: number;
  name?: string;
};

const temp = { Name: 'hj'}; 
const partialUser: PartialUser = temp; // (1)
const newUser: PartialUser = {id: 1, name: 'hd'}; // (2)

function printUserInfo(user: User) { // (3)
  console.log(`User ID: ${user.id}, Name: ${user.name}`);
}

printUserInfo(newUser); // (4)

```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
(1) 공통된 속성이 없으므로 에러 발생

(2) 에러 없음
(3) 에러 없음
(4) User 타입은 PartialUser 타입의 부분집합이므로 호환되지 않음. 에러 발생

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`1. 오류 공통속성체크`
`2. 정상`
`3. 정상`
`4. 아무것도 없을수도 있어서 오류`
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) 공통된 속성 통과 못함
<br/>
(2) 에러 없다
<br/>
(3) 에러 없다
<br/>
(4) 함수 호출 부분에서 에러
<br/>
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) 에러, 공통속성체크
(2) OK
(3) OK
(4) 에러 ..?

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1) 에러 발생. 속성이 서로 맞지 않음
2) 에러 없음
3) 에러 없음
4) 에러 발생. newUser는 User 타입보다 더 큰 PartialUser 타입이므로 



</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) 공통속성체크로 인해 오류
(2) 통과
(3) 통과
(4) 1, hd ?
</div>
</details>
