### ISSUE TITLE
[2장][지윤] 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#25]
### 퀴즈

타입스크립트에서 타입을 정의하는 방법에는 `type`과 `interface`  두 가지 방법이 있습니다.

1. 이 둘의 **공통점(1개 이상)** 과 **차이점(1개)** 을 말해주세요.

2. 다음과 같은 상황에서 `type`과 `interface` 중 어떤 것을 사용해야 좋을까요?
(1) 복잡한 타입을 사용해야 함
(2) 간단한 객체 타입
(3) api등에 대한 타입 선언 

### 답

<details>
<summary>
정답
</summary>
<div markdown="1">    
<strong>공통점</strong> <br>
1. 타입의 기본 동작
2. 인덱스 시그니처
3. 함수 타입 정의
4. 제너릭 
5. 타입 확장 가능(단, 인터페이스 유니온 제외)
6. 클래스 implements <br><br><strong>차이점</strong><br>1. 유니온 개념의 유무 <br> <code>type</code>에는 유니온 타입이 있지만, <code>interface</code>에는 유니온 인터페이스가 없다.<br>
2. <code>type</code>은 튜플과 배열 타입을 간결하게 표현할 수 있고 메서드도 사용가능, 반면 <code>interface</code>는 메서드 사용 불가<br>
3.<code>interface</code>만의 선언 병합 기능이 있다.
<br>
<br>
(1) <code>type</code><br>
(2) <code>type or interface</code> (일관성과 보강의 관점에서 둘 다 고려)<br>
(3) <code>interface</code>

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

<br>

1.  공통점: 확장을 할 수 있다. 제너릭 사용 가능하다. 클래스를 통해서 사용 가능하다. 함수 타입을 정의할 수 있다.
  차이점: 유니온 타입은 type만 가능하다. 보강은 interface만 가능하다.

2. type


</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 인덱스 시그니처 사용 가능, 보강 가능 / 불가
2.  타입, 무관, 인터페이스
</div>
</details>

**Comment by Jeong-Taeho** [comment]
(다음과 같이 답을 작성해 댓글로 달아주세요)
<details>
<summary>정답</summary>
<div markdown="1">

공통점은 서로 확장 가능,함수 타입과 인덱스 시그니처도 가능, 클래스도 가능
- type
- 아무거나
- interface
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1.
공통점
  - 차이점 빼고 다 같음..?

차이점
  - 인터페이스는 유니온이나 인터섹션으로 확장이 되지 않는다.
  - 인터페이스는 보강(선언 병합 방법으로)이 가능하다.
2.
(1) type
(2) interface
(3) interface
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1-1. 공통점: 타입 선언으로 사용이 가능하다. implements 할 수 있다.
1-2. 차이점: 인터페이스는 유니온, 인터섹션 불가능. 타입별칭은 보강(=선언병합)이 불가능
2-1. 타입
2-2. 둘 다
2-3. 인터페이스

</div>
</details>
