### ISSUE TITLE
[2장][진욱] 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by dlwl98** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#26]
### 퀴즈

```ts
interface State {
  userId: string;
  pageTitle: string;
  recentFiles: string[];
  pageContents: string;
}
```
위 코드를 참고하여 아래의 타입을 '매핑된 타입'을 이용해 만들어 보시오. (단, 유니온 타입을 사용하지 말 것)

```ts
interface NavState {
  pageTitle: string;
  recentFiles: string[];
  pageContents: string;
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

```ts
type NavState = {
  [k in Exclude<keyof State, 'userId'>]: State[k];
};
```

더 간단한 구현(하지만 매핑된 타입은 쓰지않음)
```ts
type NavState = Omit<State, 'userId'>;
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`type NavState = k in Exclude<State, 'userId'> : State[k]`
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type NavState = Exclude<keyof State, "userId">;
```

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
type NavState2 = {
  [k in keyof(State)]: k extends 'userId' ? never : State[k]
}
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
유니온 안 쓰는건 모르겠어요

```ts
type NavState = Pick<State, 'userId' | 'recentFiles' | 'pageContents'>
type  NavState = {
  [k in  'userId' | 'recentFiles' | 'pageContents']: State[k];
}

```


</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type NavState = Omit<State, 'userId'>
```

</div>
</details>
