### ISSUE TITLE
[2장][태호] 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#27]
### 퀴즈

아래와 같이 배열에 `number` 인덱스 시그니처를 사용하게 되었을 때의 단점은 무엇일까요? 간단한 해결책으로는 어떤 것이 있을 지 서술해주세요.
```ts
interface Array<T> {
   //...
   [n : number] : T;
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- 인덱스 시그니처가 number로 표현되면 입력 값이 `number`여야 하지만 실제로 런타임에서 사용되는 키는 `string` 입니다. number를 인덱스 타입으로 사용하면 `숫자 속성이 어떤 특별한 의미`를 지닌다는 오해를 일으킬 수도 있습니다.

- 인덱스 시그니처에 `number`를 사용하기보다 `Array`나 `튜플`, 또는 `ArrayLike` 타입을 사용하는 것이 좋습니다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

런타임에서 number가 string으로 변경된다.
Array, 튜플, ArrayLike를 사용한다.

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

### 단점
런타임에서 string으로 바뀌는 것이 단점이라면 단점이죠?
### 해결방법
튜플, Array, ArrayLike 타입을 사용하기

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

런타임 때는 string 타입으로 변환됨. 모름

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

interface Array 정의인데 왜 단점이죠..?
모르겠어요ㅠ

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
배열 키로 number만 적용된다는 느낌을 줘서...? /
Array, ArrayLike 사용
</div>
</details>
