### ISSUE TITLE
[2장][재희] 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#29]
### 퀴즈

아래 코드에서 getValue() 함수의 인자로 전달되는 데이터는 a, b 프로퍼티 외의 요소가 포함될 수 있고, 이 때 경고를 출력하는 함수를 작성했습니다.
추가로 들어올 프로퍼티는 string의 key로 string의 value을 가질 때, 아래 코드를 적절히 수정해 타입 체크를 통과할 수 있도록 해주세요.
```typescript
type A = {
  a: string,
  b: number
}

function getValue(x: A){
  if(Object.keys(x).length > 2) {
    console.log('임의의 데이터가 추가됐습니다.')
  }
}

getValue({
  a: '12',
  b: 12,
  c: 'hi there' // 임의의 데이터 예시 (c가 아닐 수 있음)
})
```

### 답

<details>
<summary>정답 예시</summary>
<div markdown="1">    
type A = {
  [a: string]: string | number,
  b: number
}
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
getValue({
  a: '12',
  b: 12,
  c: 'hi there'
} as A)
```

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

모루겠어요

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type A = {
  a: string
  b: number
  [otherKey: string]: string
}
```

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type A = { b: number; [key: string] : string }
```
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

인덱스 시그니처 추가
```ts
type A = {
  //... 기존코드
  [additional: string]: string | number
}
```

</div>
</details>
