### ISSUE TITLE
[1장] 타입스크립트 알아보기

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#3]
Q. 퀴즈 

`string` 또는 `number` 타입인 값을 항상 `number`로 정제하는 경우

다음은 타입 체커는 통과하지만 잘못된 방법 입니다.
올바르게 수정해주세요!
```ts
function asNumber(val: number | string): number {
  return val as number;
}
```
형식
```ts
function asNumber() {
  return
}
```

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
<img width="321" alt="image" src="https://github.com/prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study/assets/109654823/f9082631-8650-44ac-a669-42ee215908be">
</div>
</details>

**Comment by hyoribogo** [comment]
이거 아래 글 코멘트로 달아주시면 돼요 !!!
