### ISSUE TITLE
[2장][동호]: 타입스크립트의 타입 시스템

### ISSUE THREAD

**Issue by khakhiD** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#30]
### 퀴즈

아래 코드 TopNavState 인터페이스의 타입에 대한 중복을 줄여주세요.
```ts
interface State {
  userId: string;
  pageTitle: string;
  recentFiles: string[];
  pageContents: string;
}
interface TopNavState {
  userId: string;
  pageTitle: string;
  recentFiles: string[];
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

방법은 여러가지일 수 있습니다.

```ts
type TopNavState = {
  userId: State['userId'];
  pageTitle: State['pageTitle'];
  recentFiles: State['recentFiles'];
}
```

```ts
type TopNavState = {
  [k in 'userId' | 'pageTitle' | 'recentFiles']: State[k]
};
```

```ts
type TopNavState = Pick<State, 'userId' | 'pageTitle' | 'recentFiles'>;
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type TopNavState = {
  [k in 'userId' | 'pageTitle' | 'recentFiles']: State[k]
}
```

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type TopNavState = Pick<State, 'userId' | 'pageTitle' | 'recentFiles'>
type TopNavState = {
  [k in 'userId' | 'pageTitle' | 'recentFiles']: State[k];
}
```

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type TopNavState {
  [k in 'userId' | 'pageTitle' | 'recentFiles'] : State[k]
}
```
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
type TopNavState = Pick<State, 'userId' | 'pageTitle' | 'recentFiles'>
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type TopNavState = Omit<State, 'pageContents'>
```

</div>
</details>
