### ISSUE TITLE
[3장][지윤] 타입 추론

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#34]
### 퀴즈

1. 타입을 좁히는 방법에는 무엇이 있을까요?
2. `termList` 타입의 결과가 `number[]`이도록 **내장 함수**를 사용해 만들어주세요.

```ts 
function findNumberArray(terms: number|number[]){
  const termList = 
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. 조건문 사용, instanceof, 속성체크, 내장 함수, 태그된 유니온(명시적 태그, 구별된 유니온), 타입 가드(is)

2. Array.isArray 내장 함수 사용

```ts
function findNumberArray(terms: number|number[]){
  const termList = Array.isArray(terms) ? terms : [terms];
  termList // 타입이 number[]
  // ...
}
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
const termList = Array.isArray(term) ? term : [term];
```
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. instanceof, in, 반환타입 is (사용자 정의 가드), 태그된 유니온 등등 ..
2.
```ts
function findNumberArray(terms: number|number[]){
  if (Array.isArray(terms)) {
    const termList = terms
  }
}
```

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
function findNumberArray(terms: number|number[]){
  const termList = Array.isArray(terms) ? terms : [terms];
}
```

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. if() 문으로 속성이나 taggedUnion을 체크하거나... 이미 구현된 메서드를 통해 걸러내거나 등이 있을 것 같습니다.

```ts
function findNumberArray(terms: number|number[]){
  const termList = Array.isArray(terms) ? terms : [terms]
}
```

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. if문, instanceof, 타입 가드, 속성 태그, isArray 같은 함수들
2. 
```ts
function findNumberArray(terms: number|number[]){
  const termList = Array.isArray(terms) ? terms : [terms];
}
```


</div>
</details>
