### ISSUE TITLE
[3장][진욱] 타입 추론

### ISSUE THREAD

**Issue by dlwl98** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#36]
### 퀴즈

(1)과 (2)에서 `fetchState`의 타입 추론을 적으시오.

```ts
type LoadingState = { status: { label: 'loading' } };
type SuccessState = { status: { label: 'success' }; data: string };
type ErrorState = { status: { label: 'error' }; message: string };

declare let fetchState: LoadingState | SuccessState | ErrorState;

switch (fetchState.status.label) {
  case 'loading':
    console.log('로딩중..');
    break;
  case 'success':
    console.log('성공! 데이터: ', fetchState.data);  //  --- (1)
    break;
  case 'error':
    console.error('에러: ', fetchState.message);  //  --- (2)
  break;
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

(1) `LoadingState | SuccessState | ErrorState`
(2) `LoadingState | SuccessState | ErrorState`
해설: 중첩 객체에서의 태그된 유니온은 타입 좁히기가 동작하지 않습니다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

모두 label 속성을 가지고 있으므로  `LoadingState | SuccessState | ErrorState;`
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) LoadingState | SuccessState | ErrorState;
(2) LoadingState | SuccessState | ErrorState;
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) SuccessState 
(2) ErrorState

ㅡㅡ 틀림

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) SuccessState 
(2) ErrorState 

가 틀리고 다른 이유가 있을 것 같은 느낌인데 모르겠네요?
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) SuccessState 
(2) ErrorState
</div>
</details>
