### ISSUE TITLE
[3장][효리] 타입 추론

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#38]
### 퀴즈

Q. 당신은 타입스크립트입니다. 타입을 추론한 결과를 말해주세요.

```ts
let z = [1, 2, 3];   // (1) z의 타입

function add(a: number, b: number) {
    return a + b;   // (2) 반환 값의 타입
}

const data = {
    id: 1,
    name: "Alice",
    coordinates: [10, 20],
    settings: { darkMode: true, showNotifications: false },
} // (3) data의 타입

const greet = (name: string) => {
    console.log(`Hello, ${name}!`);
}; // (4) greet의 타입

const x = 'x' // (5) x의 타입

const v = {
  x: 1,
  y: 2,
} as const // (6) v의 타입


```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

(1) `number[]`
(2) `number`
(3)
```ts
{
    id: number;
    name: string;
    coordinates: number[];
    settings: {
        darkMode: boolean;
        showNotifications: boolean;
    };
}
```
(4) `(name: string) => void`
(5) `"x"`
(6) `{ readonly x: 1; readonly y: 2; }`

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
저는 타입스크립트가 아닙니다.

(1) number[]
(2) number
(3)  {
    id: number,
    name: string,
    coordinates: number[],
    settings: { darkMode: boolean, showNotifications: boolean},
}
(4) (name: string)=>void
(5) 'x'
(6)  
v = {
  readonly x: 1,
  readonly y: 2,
}
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) number[]
(2) number
(3) 
```ts
{
  id: number;
  name: string;
  coordinates: number[];
  settings: { darkMode: boolean; showNotifications: boolean };
}
```
(4) (name: string) => void
(5) 'x'
(6) 
```ts
{
  readonly x: 1;
  readonly y: 2;
}
```


</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
number[]
number
data{id: number, name: string, coordinates: number[], settings : {darkmode: boolean, showNotifications: boolean}
string
'x'
{readonly x: 1, readonly y: 2}
```
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) number[]

(2) number

(3) 
{
    id: number,
    name: string,
    coordinates: number[],
    settings: { darkMode: boolean, showNotifications: boolean },
}

(4)
const greet = (name: string) => void
반환 값 음슴

(5)
"x"

(6)
readonly x: 1;
readonly y: 2;


</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) number[]

(2) number

(3) 

```ts
id: number
name: string
coordinates: number[]
settings: {
  darkMode: boolean;
  showNotification: boolean;
}
````

(4) void
(5) x: 'x'
(6) `{readonly x: 1; readonly y:2}`


</div>
</details>
