### ISSUE TITLE
[3장][재희]: 타입 추론

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#40]
### 퀴즈

아래 코드에서 onlyNums의 타입 추론 결과를 작성하고, 에러가 나타나는 부분과 이유를 서술해주세요.

```ts
const els = ['1', 1, '2', 2];
const onlyNums = els.filter((v): v is string => typeof(v) === 'number')
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
onlyNums는 string[]으로 추론됩니다.
에러가 발생하지 않습니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

string[]
number타입을 string으로 좁혀서 에러 발생?

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
에러 없음
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts

string인데 number 여서..? 오류?

```


</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

number 값이 들어와서??
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

너무 어려워서 다 찍기

string[] | undefined

'number'에서 에러가 날거같은데 모르겠어요. string과 number 타입이 달라서 에러가 나지 않을까요  ㄷㄷ

</div>
</details>
