### ISSUE TITLE
[3장][동호]: 타입 추론

### ISSUE THREAD

**Issue by khakhiD** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#42]
### 퀴즈

```ts
declare let hasDates: boolean;

const nameTitle = { name: 'dongho', title: 'pharaoh' };
const pharaoh = {
    ...nameTitle,
    ...(hasDates ? { start: -2589, end: -2566 } : {})
};
```

위 코드에서 `pharaoh`의 타입을 추론해주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

교재에서는 다음과 같이 추론된다고 합니다.
```ts
const pharaoh: {
    start: number;
    end: number;
    name: string;
    title: string;
} | {
    name: string;
    title: string;
}
```

**그런데 실제로는 아래와 같이 추론됩니다. (해보세용)**
```ts
const pharaoh: {
    start?: number | undefined;
    end?: number | undefined;
    name: string;
    title: string;
}
```

업데이트가 된 것이 아닐까요? 같이 알아봐요...
업데이트가 된 것이라면 헬퍼 함수를 사용하지 않아도 되지 않을까요?
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
{name: string; title: string; start?: number; end?: number}

로 바뀌었다고 하네요? 몰랐습니다.
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
{
  start?: number | undefined;
  end?: number  | undefined;
  name: string;
  title: string;
}
```

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

바뀐 답
```ts
const paraoh = {
  name: string;
  title: string;
  start?: number | undefined;
  end?: number | undefined;
 }
```

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`{name: string, title: string, start?: number, end?: number}`
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`{ name: string, title: string, start?: number | undefined, end?: number | undefined }`

</div>
</details>
