### ISSUE TITLE
[4장][재희]: 타입 설계

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#44]
### 퀴즈

아래 makePair 함수의 (1)반환 타입을 예상해보고,
(2) a, b 값 중에 undefined가 있을 경우 원 함수와 같이 에러를 throw하면서 반환 타입이 [string, string]으로 추론되도록 자유롭게 코드를 수정해주세요. (타입 단언을 지양해주세요)

 ```ts
function makePair(a?: string, b?: string){
  if([a, b].includes(undefined)){
    throw new Error('cannot make pair for inputs')
  } else {
    return [a, b]
  }
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
(1) (string | undefined)[]

(2) 예시
```ts
function makePair2(a?: string, b?: string){
  let pair: null|[string, string] = null;
  if(a===undefined || b===undefined){
    throw new Error('cannot make pair for inputs')
  } else {
    pair = [a, b]
    return pair
  }
```
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) (string, undefined)[] 또는 (undefined, string)[]

(2)
```ts
function makePair(a?: string, b?: string): [string, string] {
  if (a === undefined || b === undefined) {
    throw new Error('cannot make pair for inputs');
  } else {
    return [a, b];
  }
}
```


</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) (string | undefined)[]
(2)
```ts
  function makePair(a?: string, b?: string) {
    if (!a || !b) throw new Error('cannot make pair for inputs');
    return [a, b];
  }
```

</div>
</details>
