### ISSUE TITLE
[4장][지윤] 타입 설계

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#46]
### 퀴즈

Q. 

(1) `releaseDates` 타입의 결과가 `Date[]`가 나오도록  **제너릭 매개변수**를 도입해서  `pluck` 함수를 수정해보세요.
(2) 예상되는 `pluck` 의 반환 타입은?
```ts
type RecordingType = 'studio' | 'live'

interface Album {
  artist: string
  title: string
  releaseDate: Date
  recordingType: RecordingType
}

// (1) 수정
function pluck<T>(record: T[], key: keyof T) {
  return record.map(r => r[key])
}
declare let albums: Album[]
const releaseDates = pluck(albums, 'releaseDate'); // 타입이 (string | Date)[]

pluck(albums, 'recordingType'); // (2) 반환 타입은?

}

```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

(1)
```ts
function pluck<T,K extends keyof T>(record: T[], key: K):T[K][] {
  return record.map(r => r[key])
}
const releaseDates = pluck(albums, 'releaseDate');  // 타입이 Date[]
```
(2)
```ts
RecordingType[]
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">


(1)
```ts
function pluck<T, K extends keyof T>(record: T[], key: K): T[K][] {
  return record.map(r => r[key])
}
```

(2) RecordingType[]

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
function pluck<T, K extends keyof T>(record: T[], key: K) :T[K][]{
  return record.map(r => r[key])
}
```
'studio' | 'live' 타입
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">


```ts
function pluck<T, K extends keyof T>(record: T[], key: K): T[K][] {
  return record.map(r => r[key])
}

```
(2)RecordingType[]

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1)

```ts
function pluck<T, K extends keyof T>(record: T[], key: K) {
  return record.map(r => r[key])
}
```

(2) `RecordingType[]`

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(2)  RecordingType[]
</div>
</details>
