### ISSUE TITLE
[4장][태호] 타입 설계

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#52]
### 퀴즈

`상표 기법` 에 대한 특징으로 옳지 않은 것은?
1. 타입 시스템에서 동작합니다.
2. 런타임에서 검사하는 것과 동일한 효과를 얻습니다.
3. 런타임 오버헤드를 없앨 수 있습니다.
4. 추가 속성을 붙일 수 없는 내장 타입에는 상표화할 수 없습니다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

4번
추가 속성을 붙일 수 없는 `string, number 내장 타입도 상표화가 가능`하다.

```ts
type Shoes = string & { _brand: "abc" };
type Meters = number & { _brand: "meters" };
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

4

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
4
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
4
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
4
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
 **④ 추가 속성을 붙일 수 없는 내장 타입에는 상표화할 수 없습니다.**

책에서는 number 타입에도 붙일 수 있다고 나오네요.

</div>
</details>
