### ISSUE TITLE
[5장][재희]: any 다루기

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#56]
### 퀴즈

아래 코드의 (1), (2), (3)의 타입을 추론하시오.

```ts
const result = []
result.push('a')
result // (1)
result.push(1)
result // (2)
result.push([])
result // (3)
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
(1) string[]
(2) (string|number)[]
(3) (string|number|never[])[]
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) string[]
(2) (string | number)[]
(3) (string | number | never[])[]
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) string[]
(2) (string | number)[]
(3) (string | number | any[])[]

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

string[]
number|string[]
(number|string|never[])[]
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) `string[]`

(2) `(string | number)[]`

(3) `(string | number | any[])[]`

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. string[]
2. (string | number)[]
3. ((string | number | any)[])[]

</div>
</details>
