### ISSUE TITLE
[5장][지윤] any 다루기

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#58]
### 퀴즈

1.` val`의 타입은 무엇 일까요?
```ts
funcion processValue(val: unknown){
  if(val instanceof Date){
    val // 타입은?
  }
}
```

2. (?)을 채워주세요.
(1) `{}` 타입은 (?)과 (?)를 제외한 모든 값을 포함합니다.
(2) `object` 타입은 모든 (?) 타입으로 이루어집니다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
1. Date

2-(1) `null` , `undefined`
2-(2) 비기본형(객체, 배열, 함수등)
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. Date
2. (1) null, undefined / (2) 비기본형 뭐시기

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. Date
2.
(1) {} 타입은 (null)과 (undefined)를 제외한 모든 값을 포함합니다.
(2) object 타입은 모든 (비기본형) 타입으로 이루어집니다.


</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

Date
null, undefined
비기본형
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) Date
(2-1) null, undefined
(2-2) 비기본형


</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
Date

null undefined
reference
</div>
</details>
