### ISSUE TITLE
[5장][동호]: any 다루기

### ISSUE THREAD

**Issue by khakhiD** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#61]
### 퀴즈

아래 코드에서 타입 체크 에러가 발생한다면 **①에러가 발생하는 라인**을 제시하고, **② 코드를 수정**해 주세요.

```ts
function processValues(values: any[]) {
  for (const value of values) {
    if (typeof value === 'string') {
      console.log(value.toUpperCase());
    }
  }
}

const data: unknown = [42, 'hello', true];
processValues(data);
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

타입 체크 에러가 발생합니다.

**타입 체크 에러 발생 부분**
```ts
processValues(data); // Argument of type 'unknown' is not assignable to parameter of type 'any[]'.
```

**코드 수정**
1. `data` 변수의 타입을 `unknown[]`으로 변경
2. 함수 호출부의 인수 `data`를  `any` 또는 `any[]` 또는 `unknown[]`으로 단언
3. `processValue` 함수의 매개변수 타입을 `unknown[]`으로 변경하거나 (`any`로 변경해도 에러는 안 뜸)

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

에러가 발생하는 곳: processValues(data);
수정:
```ts
function processValues(values: any[]) {
  for (const value of values) {
    if (typeof value === 'string') {
      console.log(value.toUpperCase());
    }
  }
}

const data: unknown[] = [42, 'hello', true];
processValues(data);
```

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

① processValues(data)
② const data = [42, 'hello', true]
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

unknown 부분에서 오류 발생
unknown[]
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) processValues(data) // unknown은 any[]에 할당 불가

(2) ` const data: unknown[] = [42, 'hello', true];`
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
unknown이 any[]에 할당 불가능... 배열임을 나타내주어야함.

```ts
function processValues(values: any[]) {
  for (const value of values) {
    if (typeof value === 'string') {
      console.log(value.toUpperCase());
    }
  }
}

const data: unknown[] = [42, 'hello', true];
processValues(data);
```


</div>
</details>
