### ISSUE TITLE
[5장][진욱] any 다루기

### ISSUE THREAD

**Issue by dlwl98** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#62]
### 퀴즈

다음 코드에서 오류가 나는 부분을 **모두** 찾고 이유를 쓰시오.

```ts
function fn1(x: number) {
  return x;
}

function fn2(x: any) {
  return x;
}

const a: unknown = 1;
const b: any = 1;

fn1(a); // --- (1)
fn1(b); // --- (2)
fn2(a); // --- (3)
fn2(b); // --- (4)
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

(1) 'unknown' 형식의 인수는 'number' 형식의 매개 변수에 할당될 수 없습니다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1번 -> unknown은 타입은 unknown 타입이나 any타입에만 할당될 수 있음
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) unknwon은 number에 할당 불가
(2) x
(3) x
(4) x

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

에러 발생 부분 : (1)
이유:
`unknown` 타입은 `unknown` 타입 또는 `any` 타입에만 할당 가능한데, `number`에다가 할당하려고 하는 중




</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) unknown은 number 안돼
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1) unknown은 number에 할당 불가능
(2) x
(3) x
(4) x
</div>
</details>
