### ISSUE TITLE
[5장][태호] any 다루기

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#64]
### 퀴즈

- 아래의 코드에서 `f1`과 `f2`의 반환값은 무엇일까요?  `Foo`는 `Foo` 타입을 반환합니다.

```ts
function f1() {
  const x: any = Foo();
  processBar(x);
  return x; // (1)
}

function f2() {
  const x = Foo();
  processBar(x as any);
  return x; // (2)
}
```
- 그렇다면 `f1()` 보다  `f2()` 방식이 권장되는 이유는 무엇일까요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- `f1()` : any
- `f2()` : Foo

any 타입이 processBar함수의 매개변수에서만 사용되는 표현식이므로 다른 코드에는 영향을 미치지 않기 때문이다. any를 그대로 반환하게 된다면 프로젝트 전반에 영향을 끼쳐 타입 안전성의 손실로 이어질 수 있다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1.
(1) any
(2) Foo

2. any타입의 사용을 숨겼다. any 타입의 사용범위를 줄였다. 라고 할 수 있겠습니다.

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
any, Foo
1은 이후에 사용하는 변수 x에도 영향을 끼쳐서
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) f1: any, f2: Foo
(2) 다른 코드에 영향을 주지 않아서
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(1) any
(2) Foo

any로 반환하면 문제가 전염병처럼 퍼질 가능성이 높다. 그러나 함수 내에서만 any로 단언하면 함수 외부에 영향이 가지 않기 때문에 이 방법을 사용해야 한다.
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. f1은 `any` 타입을 반환, f2는 `Foo` 타입을 반환
2. 함수의 매개변수로 any를 단언해서 사용했으므로 다른 코드에는 영향을 주지 않게 됨



</div>
</details>
