### ISSUE TITLE
[6장][재희]: 타입 선언과 @types

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#68]
### 퀴즈

아래 코드에서 getAreaFunction의 this 타입을 적절히 지정해주세요.

```ts
class Rectangle {
    private w;
    private h;

    constructor(w, h) {
        this.w = w;
        this.h = h;
    }

    getAreaFunction(this) {
        return () => {
            return this.w * this.h;
        }
    }
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

`getAreaFunction(this: Rectangle) {...} `

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

아니 왜 어렵지?

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
Rectangle 타입?

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

Rectangle

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

모르겠네요..
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
Window 타입?
```

</div>
</details>
