### ISSUE TITLE
[6장][지윤] 타입 선언과 @types

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#70]
### 퀴즈

1. 예제가 성립되도록 double 함수의 반환 타입을 **조건부 타입**을 이용해서 정의 해주세요. 

```ts
function double<T extends number | string>(x: T): ???
function double(x){
  { return x + x;}
}
// 예제
const num = double(12); // number
const str = double('x'); // string
function f(x: number | string){
  return double(x);
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

```ts 
T extends string ? string : number
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
T extends number ? number : string
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`T extends string ? string : number`
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
`T extends number | string ? string : number`
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
function double<T extends number | string>(x: T): T extends string ? string : number
function double(x){
  { return x + x;}
}
// 예제
const num = double(12); // number
const str = double('x'); // string
function f(x: number | string){
  return double(x);
}
```

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

T extends string ? string : number

</div>
</details>
