### ISSUE TITLE
[6장][태호] 타입 선언과 @types

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#73]
### 퀴즈

다음 코드에서는 이상한 결과가 나타나고 있습니다. 이러한 결과가 나타나는 이유는 무엇일까요?
```ts
function assertType<T>(x: T) {}

const double = (x: number) => 2 * x;
assertType<(a: number, b: number) => number>(double); // 정상?
```

이 코드를 제대로 체크되도록 해결하는 방법은 무엇일까요?
```ts
const double = (x: number) => 2 * x;
const p: (빈 칸을 채워주세요) = null!;  // (1)
assertType<[number, number]>(p); // '[x: number]' 형식의 인수는 '[number, number]' 형식의 매개 변수에 할당될 수 없습니다.
소스에 1개 요소가 있지만, 대상에 2개가 필요합니다.

const r: (빈 칸을 채워주세요) = null!; // (2)
assertType<number>(r); //정상
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- 타입스크립트의 함수는 매개변수가 더 적은 함수 타입에 할당 가능하기 때문입니다.
- `Paramerters<typeof double>`
- `ReturnType<typeof double>`

함수의 매개변수 타입과 반환 타입만 분리하여 테스트할 수 있습니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

매개변수가 적은 함수의 할당가능성 때문
Parameters<typeof double>
ReturnType<typeof double>

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

(0) 매개변수 개수가 작아도 오류 안뜸
(1)  `Parameters<typeof number>` ?
(2) `RetrunType<typeof number>` ?
매개변수와 리턴 타입 분리

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1) 할당 가능성을 체크하기 때문에 매개변수가 더 적어도 할당 가능하다.
2) (1) Parameters<typeof double>, ReturnType<typeof double>
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

**모르겠습니다.**

**책 확인함**
- 함수의 매개 변수가 적어도 할당이 가능하기 때문에 정상이 됨
- Parameters, ReturnType 사용


</div>
</details>
