### ISSUE TITLE
[6장][동호]: 타입 선언과 @types

### ISSUE THREAD

**Issue by khakhiD** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#74]
### 퀴즈

다음 `createLabel` 함수에는 다른 입력 타입에 따른 오버로드들이 작성되어 있습니다.
이를 interface들을 `조건부 타입`으로 수정하고 `createLabel`을 다시 작성해보세요.

```ts
interface IdLabel {
  id: number /* some fields */;
}
interface NameLabel {
  name: string /* other fields */;
}
```
```ts
function createLabel(id: number): IdLabel;
function createLabel(name: string): NameLabel;
function createLabel(nameOrId: string | number): IdLabel | NameLabel;
function createLabel(nameOrId: string | number): IdLabel | NameLabel {
  throw "unimplemented";
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

```ts
type NameOrId<T extends number | string> = T extends number
  ? IdLabel
  : NameLabel;
```
```ts
function createLabel<T extends number | string>(idOrName: T): NameOrId<T> {
  throw "unimplemented";
}
```

이 예제는 타입스크립트 공식 문서의 'Conditional Types' 챕터에서 가져왔습니다.
[링크](https://www.typescriptlang.org/ko/docs/handbook/2/conditional-types.html)

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

function createLabel<T extends string | number>(nameOrId: string | number): T extends number ? IdLabel : NameLabel

</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
function createLabel<T extends string | number>(nameOrId: T): T extends string ? NameLabel : IdLabel
function createLabel(nameOrId: any) {
  throw "unimplemented";
}
```

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
type NameOrId<T extends string | number> = T extends string ? NameLabel : IdLabel
function createLabel<T extends string | number>(x: T) : NameOrId<T>{
  //...
}
```
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. interface 조건부 타입 수정

```ts
type IdorName<T extends number | string> = T extends number ? IdLabel : NameLabel; 
```

2. createLabel을 다시 작성

```ts
function createLabel<T extends numbert |string>(nameOrId: T): IdorName<T> {
//...
}
```

</div>
</details>
