### ISSUE TITLE
[6장][효리] 타입 선언과 @types

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#75]
### 퀴즈

Q. OX 퀴즈
1. `@types` 의존성은 `dependencies`에 포함시켜야 한다.
2. TSDoc은 타입 정보를 명시해주는 것이 좋다.
3. 오버로딩 타입을 적용했을 때, 타입스크립트는 오버로딩 타입 중 일치하는 타입을 찾을 때까지 순차적으로 검색한다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. X
2. X
3. O

문제 부실해서 죄송함다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. X
2. X
3. O?
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

X X O

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- X
- X
- O
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
xxo
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
(1)x
(2)x
(3)o
</div>
</details>
