### ISSUE TITLE
[6장][진욱] 타입 선언과 @types

### ISSUE THREAD

**Issue by dlwl98** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#77]
### 퀴즈

다음 코드에서 함수 f의 반환 타입을 적고, **풀이과정**을 적으시오.
```ts
function double<T extends number | string>(
  x: T
): T extends string ? string : number;
function double(x: any) {
  return x + x;
}

function f(x: number | string) {
  return double(x);
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. 반환 타입
number | string

2. 풀이
```ts
(number | string) extends string ? string : number
(number extends string ? string : number ) | (string extends string ? string : number)
number | string
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

number | string
풀이과정은 뭐지?

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- number | string
- T extends number | string 검사 -> T extends number -> T extends string 
</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. number | string 타입
 
2. 
(1) `(number } string) extends string ? string : number`
(2)  `(number extends string ? string : number) | (string extends string ? string : number)`
(3) `number | string`
</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
number | string

number|string extends string ? string : number

number extends string -> x -> number |
string extends string -> o -> string

-> number | string

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

반환타입 **`number | string`**


**풀이과정**
- 몰겟숨



</div>
</details>
