### ISSUE TITLE
[7장][지윤] 코드를 작성하고 실행하기

### ISSUE THREAD

**Issue by JIY00N2** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#80]
### 퀴즈

다음은 문자열 열거형 `Flavor` 가 있습니다.
`scoop` 함수를 호출 할 때, 오류가 발생합니다.
**`오류가 나지 않게 하는 방법`** **또는** **`문자열 열거형을 대체할 수 있는 방법`** 을 작성해주세요.

```ts
// 문자열 열거형
const enum Flavor {
  VANILLA = 'vanilla',
  CHOCOLATE = 'chocolate',
  STRAWBERRY = 'strawberry'
}

function scoop(flavor: Flavor){}
// scoop 함수 호출
scoop('chocolate'); // 'chocolate' 형식은 'Flavor' 형식의 매개변수에 할당 될 수 없습니다.
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

```ts
// 1. Flavor 열거형의 멤버 사용
scoop(Flavor.CHOCOLATE);

// or

// 2. 리터럴 유니온 사용
type Flavor = 'vanilla' | 'chocolate' | 'strawberry';
let flavor:  Flavor = 'chocolate'


```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

 `enum` 부분을 유니온 리터럴 타입으로 만들어서 적용한다.

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
리터럴 타입의 유니온을 사용하자.

```ts
type Flavor = 'vanilla' | 'chocolate' | 'strawberry';

function scoop(flavor: Flavor){}
// scoop 함수 호출
scoop('chocolate');
```
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- import 후 scoop(Flavor.CHOCOLATE)
- `type Flavor = 'vanilla' | 'chocolate' | 'strawberry'` 리터럴 타입 유니온 사용
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. 오류가 나지 않게 하는 방법
```ts
// const enum은 preserveConstEnums였나 뭐시기 옵션 추가해야함
scoop(Flavor.CHOCOLATE)
```

2. 대체 방법
```ts
type Flavor = 'vanilla' | 'chocolate' | 'strawberry'
```

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
scoop(Flavor.CHOCOLATE)
```

</div>
</details>
