### ISSUE TITLE
[7장][태호] 코드를 작성하고 실행하기

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#82]
### 퀴즈

아래 예제를 골치 아픈 타입 문제 없이, 단순히 객체의 키와 값을 순회한다고 가정하고 가장 일반적인 방법으로 고쳐주세요.
```ts
interface ABC {
  a: string;
  b: string;
  c: number;
}

function foo(abc: ABC) {
  for (const k in abc) { // const k: string
    const v = abc[k] //'ABC' 타입에 인덱스 시그니처가 없기 때문에 엘리먼트는 암시적으로 'any'가 됩니다. 
    v // any 타입
  }
}
```

추가적으로 객체를 순회할 때, 키가 어떤 타입인지 정확히 알고 있다면 어떤 방법을 쓰면 좋을까요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

```ts
function foo(abc: ABC){
  for(const [k, v] of Object.entries(abc)){
    k // string 타입
    v // any 타입
  }
}
```
- `keyof 선언`과 `for-in` 루프
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. 
```ts
function foo(abc: ABC){
  for (const [k,v] of Object.entries(abc)){
    // ...
  }
}
 
```
2. `keyof` 사용

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
interface ABC {
  a: string;
  b: string;
  c: number;
}

function foo(abc: ABC) {
  for (const [k, v] in Object.entries(abc)) { // const k: string
    k
    v
  }
}
```

키 값 알고 있다면: `keyof ABC`
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
interface ABC {
  a: string;
  b: string;
  c: number;
}

function foo(abc: ABC) {
  for (const [k, v] of Object.entries(abc)) { 
    //
  }
}
```

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
function foo(abc: ABC) {
  for (const [k, v] of Object.entries(abc)) {
    // ...
  }
}
```

키의 타입을 정확히 알고 있다면 `keyof` 키워드 사용하기

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

```ts
function foo(abc: ABC) {
 let k: keyof typeof abc
  for (k in abc) { 
    const v = abc[k]
    v
  }
}

```


</div>
</details>
