### ISSUE TITLE
[7장][재희]: 코드를 작성하고 실행하기

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#86]
### 퀴즈

const enum은 컴파일 시에 제거됩니다.
그냥 enum은 어떻게 되나요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
javascript에는 enum이 존재하지 않으므로
객체와 즉시실행 함수를 사용하여 enum을 나타냅니다.

ex)

```ts
enum Flavor {
  VANILLA = 'vanilla',
  CHOCOLATE = 'chocolate',
  STRAWBERRY = 'strawberry'
}

->

"use strict";
var Flavor;
(function (Flavor) {
    Flavor["VANILLA"] = "vanilla";
    Flavor["CHOCOLATE"] = "chocolate";
    Flavor["STRAWBERRY"] = "strawberry";
})(Flavor || (Flavor = {}));
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

객체로 변환(?)된다.
```ts
const obj = {
  a: 1,
  b: 2,
  '1': 'a',
  '2': 'b'
}
```

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

그대로 남아있어요?

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

그대로 남는다?
모르겠어요..

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- 그냥 객체로 변환..?
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
모르겠습니다. 
</div>
</details>
