### ISSUE TITLE
[7장][동호]: 코드를 작성하고 실행하기

### ISSUE THREAD

**Issue by khakhiD** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#88]
### 퀴즈

다음 타입스크립트 코드에는 많은 에러가 발생합니다.
```ts
function handleDag(eDown: Event) {
  const targetEl = eDown.currentTarget;
  targetEl.classList.add('dragging');
  const dragStart = [eDown.clientX, eDown.clientY];
  const handleUp = (eUp: Event) => {
    targetEl.classlist.remove('dragging');
    targetEl.removeEventListener('mouseup', handleUp);
    const dragEnd = [eUp.clientX, eUp.clientY];
    console.log('dx dy = ', [0, 1].map(i => dragEnd[i] - dragStart[i]));
  }
  targetEl.addEventlistener('mouseup', handleUp);
}
```

에러가 발생하는 가장 큰 이유 2가지(어떤 이유에서 발생하는 에러인지)를 알려주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. **`targetEl`이 `null`일 가능성이 있습니다.**
(if 분기문을 통해 사용하거나, null이 아님을 확신한다면 non-null 단언문 등을 사용할 수 있습니다.)

2. **매개변수인 `eDown`은 `Event` 타입인데, `clientX`와 `clientY`는 `MouseEvent`에 존재합니다.**
(Event의 구체적 속성에 접근하기 위해서는 더 구체적인 타입을 사용해야 합니다.)

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. eDown의 타입을 MouseEvent로 하지 않아서
2. targetEl 가 null일 수 있어서

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. DOM 과 관련된 타입에 대해 falsy 값 처리를 안 해줘서
2. Event 타입이 넓어서 clientX, clientY 등을 포함하지 않을 수 있음
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. `Event`에는 `mouseEvent`에만 있는 속성이 없음다.
2. `currentTarget`으로 할당하면 `null`일 수도 있음다.

너무 광 범 위 해

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. `targetEl`이 `null`일 수 있다.
2. `Event` 타입이 너무 넓어서 -> `MouseEvent`로 좁히기


</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- targetEl은 EventTarget 속성인데 여기에는 classList 속성이 없다.
- Event 타입인 eDown, eUp에는 clientX와 같은 속성이 없다.
</div>
</details>
