### ISSUE TITLE
[7장][진욱] 코드를 작성하고 실행하기

### ISSUE THREAD

**Issue by dlwl98** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#90]
### 퀴즈

Q. 아래 코드에서 'k'의 추론되는 타입이 무엇인지 쓰고, 그렇게 추론되는 이유를 2가지 서술하시오.

```ts
interface ABC {
  a: string;
  b: string;
  c: number;
}

function foo(abc: ABC) {
  for (const k in abc) {
     //
  }
}
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

string

1. 함수는 할당 가능한 어떠한 값이든 매개변수로 허용하기 때문이다
2. 프로토타입 오염 가능성을 염두에 두었기 때문이다

퀴즈 부실해서 죄송함다..

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
string

1. 객체에 다른 값이 포함될 수 있어서,
2. 모르겠습니다
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

`string` 타입으로 추론됨

1. 키 값은 `string`이므로, 그리고 키에는 어떤 것이든 들어올 수 있으니까~ 덕 타이핑 덕 타이핑
2. 두 번째도 있나요?

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- `string`으로 추론됩니다.
- for-in문에서 객체 속성 이름을 string으로 취급하기 때문에?

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. `string` 타입
2. 
(1) 객체의 키 값은 다른 값도 들어올 수 있어서
(2) 모르겠어요.


</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- 함수의 매개변수로 쓰이는 객체에는 추가적인 속성이 존재할 수 있기 때문에
- 객체의 키 값은 `string`이기 때문에?
</div>
</details>
