### ISSUE TITLE
[8장][재희] 타입스크립트로 마이그레이션하기

### ISSUE THREAD

**Issue by oaoong** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#94]
### 퀴즈

'A <- B' 는 B 모듈이 A 모듈에 의존함을 나타냅니다. 아래 자바스크립트 모듈 의존성에 대해 타입스크립트 마이그레이션 순서를 제안해주세요.

'A<-B<-C'
'A<-D'
'E'
'B<-F'

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
제가 생각한거라 답이 맞는지는 모르겠습니다.

1. A, E
2. B, D
3. C, F

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

C D E F B A

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

A - B - C - D - F - E
?
</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- E, A, B, C, D, F? 
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

최하위 모듈부터 최상위 모듈 순으로.
1. A, E
2. B(A), D(A)
3. C(B), F(B)

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. A ,E(상관 X)
2. B,D
3. C,F

</div>
</details>
