### ISSUE TITLE
[8장][효리] 타입스크립트로 마이그레이션하기

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#97]
### 퀴즈

Q. `countWords` 함수는 의도와는 다른 값을 반환할 수도 있습니다. **그 이유를 설명**하고 **문제 상황을 해결한 코드를 작성**해 주세요.

```ts
function countWords(text: string) {
  const counts: { [word: string]: number } = {}
  for (const word of text.split(/[\s,.]+/)) {
    counts[word] = 1 + (counts[word] || 0)
  }
  return counts
}

console.log(countWords('Objects have a constructor'))

// 실행 결과 (constructor 프로퍼티 값으로 예상치 못한 결과가 나옴)
// { Objects: 1, have: 1, a: 1, constructor: '1function Object() { [native code] }' }
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

### 이유
`cunstructor`의 초기값은 `undefined`가 아닌 생성자 함수가 바인딩 된 값이기 때문에 해당 단어를 프로퍼티 키로 넣으면 의도치 않은 값을 할당하게 된다.

### 해결 코드
`Map`을 사용하면 된다.

```ts
function countWords(text: string) {
  const counts = new Map<string, number>()
  for (const word of text.split(/[\s,.]+/)) {
    counts.set(word, 1 + (counts.get(word) || 0))
  }
  return counts
}
```

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

constructor는 생성자함수이기 때문

```ts
function countWords(text: string) {
  const counts = Map<string, number>()
  for (const word of text.split(/[\s,.]+/)) {
    counts.set(word, 1 + (counts[word] || 0))
  }
  return counts
}
```

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. `constructor` 지시자는 바인딩 된 값이여서

2. Map이나 Set사용
```ts
function countWords(text: string) {
  const counts = Map<string, number>()
  for (const word of text.split(/[\s,.]+/)) {
    counts.set(word, 1 + (counts.get(word) || 0))
  }
  return counts
}
```
</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
**constructor의 초기값은 undefined가 아니라 Object.prototype에 있는 생성자 함수다.**

```tsx
// ...
const counts = new Map<string, number>()
for (const word of text.split(/[\s,.]+/)) {
  counts.set(word, 1 + (counts.get(word) || 0))
}
// ...
```

</div>
</details>

**Comment by Jeong-Taeho** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

- constructors는 프로토타입에 이미 있는 함수라서 오류가 발생
```js
function countWords(text: string) {
  const counts = Map<string, number>()
  for (const word of text.split(/[\s,.]+/)) {
    counts.set(word, 1 + (counts[word] || 0))
  }
  return counts
}
```
</div>
</details>
