### ISSUE TITLE
[8장][태호] 타입스크립트로 마이그레이션하기

### ISSUE THREAD

**Issue by Jeong-Taeho** [prgrms-web-devcourse/FEDC4-TypeScript-Kkobugi-Study#98]
### 퀴즈

자바스크립트에 `@ts-check`를 추가하여 타입을 체크하고 있습니다.
아래 오류를 해결하려면 어떻게 해야할까요?

```js
// @ts-check
const ageEl = document.getElementById('age');
ageEl.value = '12'; // HTMLElement 유형에 'value'속성이 없습니다.
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- 자바스크립트 파일이므로 `JSDoc`을 사용하여 타입 단언을 대체합니다.
```js
// @ts-check
const ageEl = /** @type {HTMLInputElement} */ document.getElementById('age');
ageEl.value = '12'; // 정상
```
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

단언문을 사용한다.
`as HTMLInputElement` 같은?

틀렸네 `JSDoc`을 사용하자~

</div>
</details>

**Comment by oaoong** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
JSDoc으로 타입을 나타내줌
</div>
</details>

**Comment by dlwl98** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

JSDoc으로 타입단언
```ts
// @ts-check
const ageEl /** @type {HTMLInputElement} */ = document.getElementById('age');
ageEl.value = '12'; // HTMLElement 유형에 'value'속성이 없습니다.
```

</div>
</details>

**Comment by JIY00N2** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

JSDoc를 사용해서 타입 단언 해준다.

</div>
</details>

**Comment by khakhiD** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

JSDoc으로 타입을 지정해줌

```tsx
// @ts-check
const ageEl = /** @type {HTMLInputElement} */(document.getElementById('age'));
ageEl.value = '12'; // 정상
```

</div>
</details>
